pub mod cpu_entropy;
pub mod entropy;

pub use entropy::{generate_random_bytes, HardwareEntropyPool};

#[cfg(test)]
mod tests {
    use rand_core_06::RngCore;
    use super::*;

    #[test]
    fn test_generate_random_bytes() {
        let bytes = generate_random_bytes(64);
        assert_eq!(bytes.len(), 64);
        assert!(bytes.iter().any(|&b| b != 0), "Generated bytes should not be all zeros");
    }

    #[test]
    fn test_hardware_entropy_pool() {
        let mut entropy_pool = HardwareEntropyPool::new();
        let mut bytes = vec![0u8; 64];
        entropy_pool.fill_bytes(&mut bytes);
        assert_eq!(bytes.iter().any(|&b| b != 0), true);
    }
}