pub mod cpu_entropy;
pub mod entropy;

pub use entropy::{fill_random_bytes, HardwareEntropyPool};

#[cfg(test)]
mod tests {
    use rand_core::Rng;
    use crate::entropy::fill_random_bytes;
    use super::*;

    #[test]
    fn test_generate_random_bytes() {
        let mut bytes = [0u8; 64];
        fill_random_bytes(&mut bytes);
        assert_eq!(bytes.len(), 64);
        assert!(bytes.iter().any(|&b| b != 0), "Generated bytes should not be all zeros");
    }

    #[test]
    fn test_hardware_entropy_pool() {
        let mut entropy_pool = HardwareEntropyPool::new();
        let mut bytes = vec![0u8; 64];
        entropy_pool.fill_bytes(&mut bytes);
        assert_eq!(bytes.iter().any(|&b| b != 0), true);
    }
}